# Generated by Django 4.0.6 on 2022-07-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuposition',
            old_name='price',
            new_name='Price',
        ),
        migrations.AddField(
            model_name='menuposition',
            name='Title',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
    ]
