# Generated by Django 4.0.6 on 2022-07-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menuposition_price_remove_menuposition_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuposition',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='menuposition',
            name='bonus_increment',
            field=models.IntegerField(default=0, verbose_name='+Bonuses'),
        ),
        migrations.AddField(
            model_name='menuposition',
            name='menu_type',
            field=models.CharField(default=0, max_length=10, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuposition',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
