# Generated by Django 4.0.6 on 2022-07-25 11:31

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuposition_is_active_alter_menuposition_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuposition',
            name='image',
            field=models.ImageField(blank=True, upload_to=menu.models.image_directory_path, verbose_name='Picture'),
        ),
    ]
