# Generated by Django 4.0.6 on 2022-07-25 11:50

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menuposition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuposition',
            name='image',
            field=models.ImageField(upload_to=menu.models.directory_path, verbose_name='Picture'),
        ),
    ]
