# Generated by Django 4.0.6 on 2022-07-26 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=10, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='menuposition',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.category'),
        ),
    ]
