# Generated by Django 4.0.6 on 2022-07-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_category_options_alter_menuposition_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuposition',
            name='icon',
        ),
    ]
