# Generated by Django 4.0.6 on 2022-07-27 19:01

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_remove_menuposition_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuposition',
            name='icon',
            field=models.ImageField(default='/', upload_to=menu.models.icon_directory_path, verbose_name='Icon'),
            preserve_default=False,
        ),
    ]
