# Generated by Django 4.0.6 on 2022-07-27 19:31

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_alter_menuposition_icon_alter_menuposition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuposition',
            name='icon',
            field=models.FileField(null=True, upload_to=menu.models.icon_directory_path, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='menuposition',
            name='image',
            field=models.ImageField(null=True, upload_to=menu.models.image_directory_path, verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='menuposition',
            name='weight',
            field=models.IntegerField(null=True, verbose_name='Weight'),
        ),
    ]
