# Generated by Django 4.0.6 on 2022-07-31 15:40

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_alter_menuposition_icon_alter_menuposition_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuposition',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, upload_to=menu.models.icon_directory_path, verbose_name='Icon'),
        ),
    ]
