# Generated by Django 4.0.6 on 2022-07-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_remove_menuposition_icon_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default='', max_length=16, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=16, verbose_name='Category'),
        ),
    ]
